### ISSUE TITLE
sign up error

### ISSUE THREAD

**Issue by ublockme** [Charles042/SocialMedia-App#1]
Hi there! I like your app really. I tried to use your source code. when I was sign up in emulator, I'm getting error like this.

![image](https://user-images.githubusercontent.com/79246685/115179727-9b6b6000-a0f1-11eb-9884-1d58e2d76941.png)

I'm new for flutter and firebase. can you guide me to solve this error?

**Comment by ublockme** [comment]
Now i cleared it..

**Comment by madd-project** [comment]
how @ublockme

**Comment by Charles042** [comment]
Hello..
Please I'd suggest you be patient so i can make a new update that is
compatible with flutter 2.
But if you have the old sdk, you can switch to it and run the code i think
it'll definitely run smoothly.

**Comment by Charles042** [comment]
Hello,
I hope you're well?.
I've pushed a new commit to the social media
Is now compatible with flutter 2.
