### ISSUE TITLE
Posting have errors

### ISSUE THREAD

**Issue by vindicta43** [Charles042/SocialMedia-App#11]
I'm getting this error

`
E/AndroidRuntime(32258): FATAL EXCEPTION: main
E/AndroidRuntime(32258): Process: com.example.social_media, PID: 32258
E/AndroidRuntime(32258): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=69, result=0, data=null} to activity {com.example.social_media/com.example.social_media.MainActivity}: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(32258): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5143)
E/AndroidRuntime(32258): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5184)
E/AndroidRuntime(32258): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime(32258): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:140)
E/AndroidRuntime(32258): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:100)
E/AndroidRuntime(32258): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2222)
E/AndroidRuntime(32258): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(32258): 	at android.os.Looper.loop(Looper.java:228)
E/AndroidRuntime(32258): 	at android.app.ActivityThread.main(ActivityThread.java:7782)
E/AndroidRuntime(32258): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(32258): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(32258): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
E/AndroidRuntime(32258): Caused by: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(32258): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:155)
E/AndroidRuntime(32258): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:238)
E/AndroidRuntime(32258): 	at vn.hunghd.flutter.plugins.imagecropper.ImageCropperDelegate.onActivityResult(ImageCropperDelegate.java:106)
E/AndroidRuntime(32258): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:739)
E/AndroidRuntime(32258): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:426)
E/AndroidRuntime(32258): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:677)
E/AndroidRuntime(32258): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:624)
E/AndroidRuntime(32258): 	at android.app.Activity.dispatchActivityResult(Activity.java:8304)
E/AndroidRuntime(32258): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5136)
E/AndroidRuntime(32258): 	... 11 more
E/flutter (32258): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: 'package:flutter/src/material/scaffold.dart': Failed assertion: line 222 pos 12: 'context != null': is not true.
E/flutter (32258): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
E/flutter (32258): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter (32258): #2      ScaffoldMessenger.of (package:flutter/src/material/scaffold.dart:222:12)
E/flutter (32258): #3      StoryViewModel.showInSnackBar (package:social_media/view_models/posts/story_view_model.dart:119:23)
E/flutter (32258): #4      StoryViewModel.pickImage (package:social_media/view_models/posts/story_view_model.dart:90:7)
E/flutter (32258): <asynchronous suspension>
E/flutter (32258): #5      FabContainer.chooseUpload.<anonymous closure>.<anonymous closure> (package:social_media/components/fab_container.dart:80:19)
E/flutter (32258): <asynchronous suspension>
E/flutter (32258): 
I/Process (32258): Sending signal. PID: 32258 SIG: 9
Lost connection to device.
`

**Comment by Charles042** [comment]
Hello!.

The story functionality is still a work on progress, i think you're trying
to upload to stories.
